name: BuildAndRunTests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - source/**
  pull_request:
    branches: [ "main" ]
    paths:
    - source/**
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Iciclecreek.Json.Net.DependencyInjection
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore source/Iciclecreek.Json.Net.DependencyInjection.sln 

    - name: Build
      run: dotnet build --no-restore source/Iciclecreek.Json.Net.DependencyInjection.sln --property WarningLevel=0
      
    - name: Test
      run: dotnet test --no-build --verbosity normal source/Iciclecreek.Json.Net.DependencyInjection.sln
